image:
  repository: tccr.io/truecharts/minio
  tag: latest@sha256:238d46433a4164faf725bcf04848c8b7136687532a80f2103ac1734e94768cd2
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10106
        targetPort: 10106
  web:
    enabled: true
    ports:
      web:
        enabled: true
        targetPort: 10107
        port: 10107
ingress:
  web:
    autoLink: true
persistence:
  config:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              custom: true
              spec:
                httpGet:
                  scheme: HTTP
                  path: "/minio/health/live"
                  port: 10106
            readiness:
              custom: true
              spec:
                httpGet:
                  scheme: HTTP
                  path: "/minio/health/ready"
                  port: 10106
          args:
            - "server"
            - "/data"
            - "--address"
            - ":10106"
            - "--console-address"
            - ":10107"
          env:
            MINIO_ROOT_USER: "minio"
            MINIO_BROWSER_REDIRECT_URL: ""
            MINIO_SERVER_URL: ""
            MINIO_ROOT_PASSWORD: "changeme"
